import { environment } from '../environments/environment';

export const BASE_URL = environment.BASE_URL;
export const STATE_LIST = ['In progress', 'Completed'];
export const ROLE_LIST = ['NORMAL', 'ADMIN'];
export const LEAVE_TYPE_LIST = ['All', 'Planned', 'Un-Planned'];
export const STATUS_ROW_COUNT = 6;
export const SUNDAY = 0;
export const MONDAY = 1;
export const TUESDAY = 2;
export const WEDNESDAY = 3;
export const THRUSDAY = 4;
export const FRIDAY = 5;
export const SATURDAY = 6;
export const FULLDAY_LIST = 0;
export const HALFDAY_LIST = 1;
export const HOLIDAY_LIST = 2;
export const DEFAULT_USER_TYPE = 'All';
export const PREV = 'PREV';
export const NEXT = 'NEXT';
export const HOLIDAY_COLOR = '#f48b29';
export const DARK_GREY = '#545b62';
export const FULL_DAY_LEAVE_INDEX = 0;
export const HALF_DAY_LEAVE_INDEX = 1;
export const FULL_DAY_LABEL = 'full-day';
export const HALF_DAY_LABEL = 'half-day';
export const NOT_APPLICABLE = 'Not Applicable';
